// Dicionário de headlines (sem IA, sem custo). Fácil de editar: acrescente um tipo com
// palavras-chave (sem acento, minúsculas; o plural "s"/"es" já é aceito) e 3 a 5 headlines
// em MAIÚSCULAS com 1 emoji no final. Tipos escolhidos pelos títulos reais do catálogo (10/2026).
//
// Busca: vence a palavra-chave que aparece MAIS CEDO no título; empate -> a mais longa
// (mais específica, ex.: "tenis de corrida" antes de "tenis").
import type { CatalogCategory } from "@achadinhos/db";

export interface HeadlineType {
  key: string;
  category: Exclude<CatalogCategory, "OTHER"> | "OTHER";
  keywords: string[];
  /** Neutras (valem para qualquer público). */
  headlines: string[];
  /** Só quando o título diz "feminino" ou "mulher". */
  feminine?: string[];
  /** Só quando o título diz "masculino" ou "homem". */
  masculine?: string[];
}

/** Gênero no título: só "feminino/mulher" ou "masculino/homem" ativam headlines com gênero. */
/**
 * Palavra-chave que NÃO conta quando vem logo depois destas palavras (sem acento, minúsculas).
 * Ex.: "barata" de "mais barata" / "opção barata" é preço, não inseto.
 */
export const KEYWORD_NOT_AFTER: Record<string, string[]> = {
  barata: ["mais", "bem", "muito", "super", "mega", "tao", "opcao", "versao", "alternativa", "solucao", "e", "ultra"],
};

export const FEMININE_WORDS = ["feminino", "feminina", "femininos", "femininas", "mulher", "mulheres"];
export const MASCULINE_WORDS = ["masculino", "masculina", "masculinos", "masculinas", "homem", "homens"];

export const PRODUCT_TYPES: HeadlineType[] = [
  // ---------- Alimentos e Bebidas ----------
  { key: "cafe", category: "FOOD_BEVERAGES", keywords: ["cafe", "capsula de cafe", "capsulas de cafe", "nescafe", "cafe soluvel", "cafe em graos"], headlines: ["O CAFEZINHO QUE VOCÊ MERECE ☕", "ENERGIA PARA COMEÇAR O DIA ☕", "AROMA DE CAFÉ FRESQUINHO EM CASA ☕", "PAUSA PARA UM CAFÉ ESPECIAL ☕"] },
  { key: "chocolate", category: "FOOD_BEVERAGES", keywords: ["chocolate", "bombom", "barra de chocolate", "tablete", "lacta", "kit kat", "trufa", "cacau"], headlines: ["MOMENTO DOCE GARANTIDO 🍫", "CHOCOLATE PARA ADOÇAR O DIA 🍫", "IMPOSSÍVEL COMER SÓ UM 😋", "O MIMO QUE TODO MUNDO AMA 🍫"] },
  { key: "doces", category: "FOOD_BEVERAGES", keywords: ["bala", "pirulito", "chiclete", "mentos", "doce de leite", "pacoca", "goma", "marshmallow", "doce"], headlines: ["DOÇURA PARA QUALQUER HORA 🍬", "PARA MATAR A VONTADE DE DOCE 😋", "ALEGRIA EM FORMA DE DOCE 🍭", "O DOCINHO QUE FALTAVA 🍬"] },
  { key: "biscoito", category: "FOOD_BEVERAGES", keywords: ["biscoito", "bolacha", "cookie", "wafer", "rosquinha"], headlines: ["CROCANTE DO JEITO QUE VOCÊ GOSTA 🍪", "PARCEIRO PERFEITO DO CAFÉ 🍪", "LANCHINHO GARANTIDO 😋"] },
  { key: "azeite", category: "FOOD_BEVERAGES", keywords: ["azeite", "azeite de oliva", "oleo de coco"], headlines: ["SABOR DE VERDADE NA SUA COZINHA 🫒", "O TOQUE ESPECIAL DOS SEUS PRATOS 🫒", "QUALIDADE QUE FAZ DIFERENÇA NA RECEITA 🍽️"] },
  { key: "temperos", category: "FOOD_BEVERAGES", keywords: ["tempero", "ketchup", "maionese", "mostarda", "molho", "heinz", "pimenta", "sal rosa", "condimento", "caldo"], headlines: ["MAIS SABOR EM CADA REFEIÇÃO 🍽️", "O SEGREDO DO PRATO PERFEITO 👨‍🍳", "TEMPERO QUE FAZ A DIFERENÇA 🌶️"] },
  { key: "achocolatado-leite", category: "FOOD_BEVERAGES", keywords: ["achocolatado", "leite em po", "ninho", "nescau", "toddy", "composto lacteo", "leite condensado", "creme de leite"], headlines: ["NUTRIÇÃO GOSTOSA PARA A FAMÍLIA 🥛", "O SABOR DA INFÂNCIA DE VOLTA 🥛", "ESTOQUE A DESPENSA COM ECONOMIA 🛒"] },
  { key: "cereais-graos", category: "FOOD_BEVERAGES", keywords: ["granola", "aveia", "cereal", "arroz", "feijao", "macarrao", "farinha", "castanha", "amendoim", "mix de nuts", "pasta de amendoim"], headlines: ["ENCHA A DESPENSA E ECONOMIZE 🛒", "BASE DE UMA ALIMENTAÇÃO GOSTOSA 🥣", "PRATICIDADE PARA O DIA A DIA 🛒"] },
  { key: "mel-geleia", category: "FOOD_BEVERAGES", keywords: ["mel", "geleia", "doce de fruta", "melado"], headlines: ["DOÇURA NATURAL PARA O SEU DIA 🍯", "O TOQUE ESPECIAL DO CAFÉ DA MANHÃ 🍯", "SABOR CASEIRO NA SUA MESA 🍯"] },
  { key: "bebida-alcoolica", category: "FOOD_BEVERAGES", keywords: ["vinho", "whisky", "vodka", "gin", "cerveja", "cachaca", "espumante", "licor", "rum", "tequila"], headlines: ["PARA BRINDAR OS BONS MOMENTOS 🥂", "A BEBIDA CERTA PARA O SEU ROLÊ 🍷", "CELEBRE COM ESTILO 🥂", "SELEÇÃO ESPECIAL PARA O FIM DE SEMANA 🍷"] },
  { key: "bebida", category: "FOOD_BEVERAGES", keywords: ["energetico", "monster", "red bull", "refrigerante", "suco", "cha", "agua de coco", "isotonico", "yopro", "bebida lactea"], headlines: ["REFRESCÂNCIA NA MEDIDA CERTA 🥤", "ENERGIA PARA O SEU DIA ⚡", "GELADINHO NA HORA QUE QUISER 🥤"] },
  { key: "cobertura-confeitaria", category: "FOOD_BEVERAGES", keywords: ["cobertura", "granulado", "confeito", "fermento", "leite de coco", "chantilly", "corante alimenticio"], headlines: ["SUA RECEITA AINDA MAIS GOSTOSA 🎂", "CONFEITARIA DE RESPEITO EM CASA 🧁", "PARA OS DOCES FICAREM PERFEITOS 🎂"] },
  { key: "snacks", category: "FOOD_BEVERAGES", keywords: ["salgadinho", "batata chips", "pipoca", "snack", "amendoim japones", "torrada"], headlines: ["O PETISCO QUE NÃO PODE FALTAR 🍿", "HORA DO LANCHINHO 😋", "PERFEITO PARA MARATONAR SÉRIES 🍿"] },

  // ---------- Beleza ----------
  { key: "perfume", category: "BEAUTY", keywords: ["desodorante colonia", "deo colonia", "deo parfum", "perfume", "eau de parfum", "eau de toilette", "colonia", "deo colonia", "body splash", "lattafa", "fragrancia", "body mist"], headlines: ["CHEIRO QUE DEIXA MARCA ✨", "SUA ASSINATURA EM FORMA DE PERFUME 💫", "PERFUME QUE ACOMPANHA O DIA INTEIRO 🌸", "FRAGRÂNCIA QUE CONQUISTA 💐"], feminine: ["PERFUME FEMININO QUE CONQUISTA 💐","PARA ELA SE SENTIR INCRÍVEL ✨"], masculine: ["PERFUME MASCULINO MARCANTE 🖤","PARA ELE ARRASAR NO CHEIRO 🔥"] },
  { key: "skincare-serum", category: "BEAUTY", keywords: ["serum", "vitamina c facial", "acido hialuronico", "niacinamida", "retinol", "principia", "ampola facial", "esfoliante facial", "agua micelar", "tonico facial", "skincare"], headlines: ["SUA ROTINA DE SKINCARE MAIS COMPLETA ✨", "UM CUIDADO A MAIS PARA A SUA PELE 💧", "ROTINA DE SKINCARE DE RESPEITO 🧴", "O QUERIDINHO DO SKINCARE ✨"] },
  { key: "protetor-solar", category: "BEAUTY", keywords: ["protetor solar", "filtro solar", "fps", "bloqueador solar", "anthelios"], headlines: ["PROTETOR SOLAR PARA A SUA ROTINA ☀️", "NÃO SAIA DE CASA SEM ELE ☀️", "INDISPENSÁVEL TODO DIA ☀️"] },
  { key: "hidratante", category: "BEAUTY", keywords: ["hidratante", "creme hidratante", "locao", "manteiga corporal", "nivea", "cerave", "creme para maos", "creme facial", "creme"], headlines: ["HIDRATANTE PARA A SUA ROTINA 💧", "TEXTURA GOSTOSA DE PASSAR 💧", "UM CARINHO NA SUA ROTINA 🧴"] },
  { key: "maquiagem-boca", category: "BEAUTY", keywords: ["hidratante labial", "protetor labial", "batom", "gloss", "lip", "lip tint", "lip oil", "lapis labial", "balm"], headlines: ["BOCA LINDA EM SEGUNDOS 💋", "O TOQUE FINAL DO SEU LOOK 💄", "BRILHO E COR SEM ESFORÇO 💋"] },
  { key: "maquiagem-olhos", category: "BEAUTY", keywords: ["mascara de cilios", "rimel", "delineador", "sombra", "paleta de sombras", "cilios postiços", "cilios", "sobrancelha", "henna", "lapis de olho"], headlines: ["OLHAR PODEROSO EM MINUTOS 👁️", "OLHOS QUE CHAMAM ATENÇÃO ✨", "MAKE DOS OLHOS SEM COMPLICAÇÃO 💄"] },
  { key: "maquiagem-pele", category: "BEAUTY", keywords: ["base liquida", "base", "corretivo", "po compacto", "po facial", "blush", "iluminador", "primer", "bronzer", "contorno", "fixador de maquiagem"], headlines: ["MAKE BONITA E PRÁTICA ✨", "ACABAMENTO DE PROFISSIONAL 💄", "MAKE QUE DURA O DIA TODO 💫"] },
  { key: "pincel-maquiagem", category: "BEAUTY", keywords: ["pincel", "kit de pinceis", "esponja de maquiagem", "beauty blender"], headlines: ["MAKE DE PROFISSIONAL EM CASA 💄", "ACABAMENTO IMPECÁVEL NA SUA MAKE ✨", "FERRAMENTA CERTA PARA ARRASAR 💅"] },
  { key: "unhas", category: "BEAUTY", keywords: ["esmalte", "kit manicure", "unha postiça", "gel para unhas", "cabine led", "lixa de unha", "alicate de cuticula"], headlines: ["UNHAS DE SALÃO EM CASA 💅", "MÃOS LINDAS EM POUCOS MINUTOS 💅", "COR NOVA PARA AS SUAS UNHAS 💅"] },
  { key: "cabelo-shampoo", category: "BEAUTY", keywords: ["shampoo", "condicionador", "mascara capilar", "leave in", "creme de pentear", "oleo capilar", "kit capilar", "tonico capilar", "ampola capilar", "reparador de pontas", "oleo reparador"], headlines: ["UM CUIDADO A MAIS PARA OS FIOS 💆", "ROTINA CAPILAR COMPLETA ✨", "MOMENTO DE SALÃO EM CASA 💇", "O QUERIDINHO DA ROTINA CAPILAR ✨"] },
  { key: "tintura", category: "BEAUTY", keywords: ["tintura", "coloracao", "descolorante", "tonalizante"], headlines: ["COR NOVA SEM SAIR DE CASA 💇", "MUDE O VISUAL COM PRATICIDADE ✨", "PRATICIDADE PARA COLORIR OS FIOS 💖"] },
  { key: "secador-chapinha", category: "BEAUTY", keywords: ["secador de cabelo", "secador", "chapinha", "prancha alisadora", "babyliss", "modelador de cachos", "escova secadora", "escova rotativa"], headlines: ["PENTEADO DE SALÃO EM CASA 💇", "PRATICIDADE PARA MODELAR OS FIOS ✨", "PRATICIDADE PARA ARRASAR NO VISUAL ✨"] },
  { key: "escova-cabelo", category: "BEAUTY", keywords: ["escova de cabelo", "pente", "escova raquete", "escova desembaracadora"], headlines: ["PRATICIDADE PARA PENTEAR 💆", "O ACESSÓRIO QUE SEU CABELO PEDE ✨", "PRÁTICA PARA O DIA A DIA 💇"] },
  { key: "desodorante", category: "BEAUTY", keywords: ["desodorante", "antitranspirante", "deo", "rexona", "dove"], headlines: ["FRESCOR PARA A SUA ROTINA 💪", "FRESCOR NA MEDIDA CERTA 🌿", "O BÁSICO QUE NÃO PODE FALTAR ✨"], feminine: ["FRESCOR PARA A ROTINA DELA 🌸"], masculine: ["FRESCOR PARA A ROTINA DELE 🌿"] },
  { key: "sabonete", category: "BEAUTY", keywords: ["sabonete", "sabonete liquido", "gel de banho", "esfoliante corporal", "sais de banho"], headlines: ["BANHO RELAXANTE E PERFUMADO 🛁", "BANHO CHEIROSO E GOSTOSO 🧼", "AUTOCUIDADO NA HORA DO BANHO 🛁"] },
  { key: "barba", category: "BEAUTY", keywords: ["barbeador", "aparador de barba", "maquina de barbear", "oleo para barba", "balm para barba", "lamina de barbear", "gilette", "gillette"], headlines: ["BARBA ALINHADA SEM SAIR DE CASA 🧔", "VISUAL IMPECÁVEL TODO DIA 💈", "CUIDADO COMPLETO PARA A BARBA 🧔"], masculine: ["CUIDADO MASCULINO DE RESPEITO 🧔"] },
  { key: "depilacao", category: "BEAUTY", keywords: ["depilador", "cera depilatoria", "depilacao", "epilador", "luz pulsada"], headlines: ["PRATICIDADE NA SUA ROTINA ✨", "DEPILAÇÃO PRÁTICA EM CASA ✨", "MAIS PRATICIDADE NO SEU AUTOCUIDADO ✨"] },
  { key: "necessaire", category: "BEAUTY", keywords: ["necessaire", "porta maquiagem", "organizador de maquiagem", "maleta de maquiagem"], headlines: ["TUDO ORGANIZADO NA SUA BOLSA 👜", "SEUS ITENS DE BELEZA NO LUGAR CERTO 💄", "PRATICIDADE PARA VIAJAR ✈️"] },
  { key: "aromatizador", category: "BEAUTY", keywords: ["essencia", "aromatizador", "home spray", "difusor de aromas", "difusor", "vela aromatica", "cheirinho para carro", "sache perfumado"], headlines: ["CASA SEMPRE CHEIROSA 🌸", "PERFUME PARA O SEU AMBIENTE 🕯️", "AROMA QUE ACOLHE QUEM CHEGA 🌿"] },
  { key: "espelho-maquiagem", category: "BEAUTY", keywords: ["espelho de maquiagem", "espelho com led", "ring light"], headlines: ["MAKE PERFEITA COM A LUZ CERTA 💡", "ACABAMENTO DE ESTÚDIO EM CASA ✨", "CADA DETALHE NO LUGAR 💄"] },

  // ---------- Saúde e suplementos ----------
  { key: "whey", category: "HEALTH", keywords: ["whey", "whey protein", "proteina", "protein", "albumina", "isolado proteico"], headlines: ["PROTEÍNA DE QUALIDADE PARA O SEU TREINO 💪", "PRATICIDADE PARA A SUA ROTINA DE TREINO 💪", "SABOR E PRATICIDADE NO PÓS-TREINO 🏋️", "O SUPLEMENTO QUE CABE NA SUA ROTINA 🥤"] },
  { key: "creatina", category: "HEALTH", keywords: ["creatina", "creapure", "monohidratada"], headlines: ["PRATICIDADE NA SUA SUPLEMENTAÇÃO 💪", "O SUPLEMENTO QUE NÃO PODE FALTAR 🏋️", "UM CLÁSSICO DA ROTINA DE TREINO 🏋️"] },
  { key: "pre-treino", category: "HEALTH", keywords: ["pre treino", "pre workout", "termogenico", "cafeina", "beta alanina", "bcaa", "glutamina", "hipercalorico", "mass", "barra de proteina", "barra proteica"], headlines: ["PRATICIDADE ANTES DO TREINO ⚡", "PARA QUEM NÃO ABRE MÃO DO TREINO 🔥", "SUPLEMENTO PARA A SUA ROTINA DE TREINO 💪"] },
  { key: "vitaminas", category: "HEALTH", keywords: ["vitamina", "multivitaminico", "complexo b", "vitamina d", "vitamina c", "magnesio", "zinco", "omega", "omega 3", "biotina", "colageno", "coenzima", "adenosilcobalamina", "ferro", "calcio", "suplemento", "melatonina", "probiotico", "cloreto de magnesio"], headlines: ["CUIDADO DIÁRIO COM PRATICIDADE 💊", "UM CUIDADO A MAIS NA SUA ROTINA 🌿", "PRATICIDADE PARA A SUA ROTINA DE CUIDADOS ⚡", "SUA ROTINA DE CUIDADOS MAIS PRÁTICA 💚"] },
  { key: "massageador", category: "HEALTH", keywords: ["massageador", "pistola de massagem", "massageador eletrico", "massageador de pescoco", "rolo de massagem", "almofada massageadora"], headlines: ["MOMENTO DE CUIDADO DEPOIS DO DIA PUXADO 💆", "SPA EM CASA QUANDO QUISER 💆", "CONFORTO PARA O SEU DIA A DIA 😌", "SEU MOMENTO DE AUTOCUIDADO 🙌"] },
  { key: "balanca", category: "HEALTH", keywords: ["balanca", "balanca digital", "balanca de bioimpedancia", "balanca de cozinha"], headlines: ["ACOMPANHE SUA EVOLUÇÃO DE PERTO 📊", "PRECISÃO PARA O SEU DIA A DIA ⚖️", "CONTROLE NA PALMA DA MÃO 📲"] },
  { key: "saude-aparelho", category: "HEALTH", keywords: ["monitor de glicose", "monitor de pressao", "monitor cardiaco", "tiras de glicose", "lancetas", "medidor de pressao", "termometro", "oximetro", "inalador", "nebulizador", "aparelho de pressao", "glicosimetro", "umidificador", "purificador de ar"], headlines: ["PRATICIDADE PARA OS CUIDADOS EM CASA 🩺", "TRANQUILIDADE PARA O DIA A DIA 💙", "ITEM ESSENCIAL PARA A SUA CASA 🩺"] },
  { key: "pomada-remedio", category: "HEALTH", keywords: ["pomada", "gel", "spray anti inflamatorio", "curativo", "esparadrapo", "band aid", "soro fisiologico", "colirio", "seringa"], headlines: ["PRATICIDADE PARA A FARMACINHA DE CASA 🩹", "ITEM QUE NÃO PODE FALTAR NA FARMACINHA 💊", "CUIDADO RÁPIDO E PRÁTICO 🩹"] },
  { key: "higiene-bucal", category: "HEALTH", keywords: ["escova de dente", "escova dental", "escova eletrica", "creme dental", "pasta de dente", "fio dental", "enxaguante bucal", "colgate", "oral b", "irrigador oral", "clareador dental"], headlines: ["CUIDADO DIÁRIO COM O SEU SORRISO 😁", "PRATICIDADE NA ROTINA DE HIGIENE BUCAL 🦷", "ROTINA DE HIGIENE BUCAL COMPLETA 😁"] },
  { key: "fitness", category: "HEALTH", keywords: ["halter", "anilha", "kettlebell", "elastico de treino", "corda de pular", "tapete de yoga", "colchonete", "faixa elastica", "barra fixa", "garrafa de academia", "coqueteleira", "luva de academia", "academia"], headlines: ["TREINE EM CASA SEM DESCULPA 🏋️", "SEU TREINO EM CASA MAIS PRÁTICO 💪", "EQUIPAMENTO PRÁTICO PARA TREINAR 🔥"] },
  { key: "porta-comprimidos", category: "HEALTH", keywords: ["porta comprimidos", "porta comprimido", "porta remedio", "porta remedios", "porta medicamento", "organizador de remedios", "caixa de remedios"], headlines: ["SEUS REMÉDIOS SEMPRE ORGANIZADOS 💊", "PRATICIDADE PARA A ROTINA DE CUIDADOS 💊", "CABE NA BOLSA E NA VIAGEM ✈️"] },
  { key: "absorvente-higiene", category: "HEALTH", keywords: ["absorvente", "protetor diario", "coletor menstrual", "fralda geriatrica", "papel higienico", "lenco umedecido adulto"], headlines: ["CONFORTO E PROTEÇÃO NO SEU DIA 💙", "ESTOQUE GARANTIDO COM ECONOMIA 🛒", "PRATICIDADE PARA A ROTINA ✨"] },

  // ---------- Casa, Cozinha e Decoração ----------
  { key: "panelas", category: "HOME_KITCHEN_DECOR", keywords: ["panela", "jogo de panelas", "conjunto de panelas", "panela de pressao", "panela antiaderente", "caçarola", "cacarola", "frigideira", "wok", "caldeirao"], headlines: ["COZINHA COMPLETA PARA CHEFS DE VERDADE 👨‍🍳", "COZINHAR NUNCA FOI TÃO GOSTOSO 🍳", "NADA GRUDA, TUDO FICA PERFEITO 🍳", "RENOVE SUA COZINHA COM ESTILO ✨"] },
  { key: "airfryer", category: "HOME_KITCHEN_DECOR", keywords: ["air fryer", "airfryer", "fritadeira", "fritadeira eletrica", "fritadeira sem oleo", "forno eletrico", "forno air fryer"], headlines: ["FRITURA SEM ÓLEO, SABOR DE VERDADE 🍟", "REFEIÇÕES RÁPIDAS SEM COMPLICAÇÃO 🔥", "A QUERIDINHA DA COZINHA 🍗", "PRATICIDADE QUE MUDA SUA ROTINA ⏱️"] },
  { key: "eletroportateis", category: "HOME_KITCHEN_DECOR", keywords: ["liquidificador", "batedeira", "mixer", "processador", "multiprocessador", "espremedor", "sanduicheira", "grill", "torradeira", "panela eletrica", "cafeteira", "chaleira", "chaleira eletrica", "microondas", "micro ondas", "pipoqueira"], headlines: ["SUA COZINHA MAIS PRÁTICA ⚡", "FAZ O TRABALHO PESADO POR VOCÊ 💪", "PRATICIDADE NO DIA A DIA DA COZINHA ⚡", "MAIS TEMPO PARA VOCÊ, MENOS NA COZINHA ⏱️"] },
  { key: "potes", category: "HOME_KITCHEN_DECOR", keywords: ["pote", "pote hermetico", "potes de vidro", "marmita", "conjunto de potes", "porta mantimentos", "porta tempero", "porta temperos", "galheteiro"], headlines: ["COZINHA ORGANIZADA E ALIMENTOS FRESCOS 🥗", "TUDO NO LUGAR E À MOSTRA ✨", "ADEUS BAGUNÇA NA DESPENSA 🙌", "ORGANIZAÇÃO QUE DÁ GOSTO DE VER 😍"] },
  { key: "organizador", category: "HOME_KITCHEN_DECOR", keywords: ["saquinho organizador", "organizador", "organizadora", "caixa organizadora", "cesto", "nicho", "prateleira", "gancho", "suporte de parede", "suporte adesivo", "cabide", "sapateira", "porta objetos", "escorredor", "porta pano"], headlines: ["CASA ORGANIZADA, VIDA LEVE ✨", "CADA COISA NO SEU LUGAR 🙌", "MAIS ESPAÇO, MENOS BAGUNÇA 📦", "ORGANIZAÇÃO QUE TRANSFORMA SUA CASA 🏡"] },
  { key: "garrafa-termica", category: "HOME_KITCHEN_DECOR", keywords: ["garrafa termica", "garrafa", "copo termico", "squeeze", "stanley", "caneca termica", "termolar", "copo stanley"], headlines: ["SUA BEBIDA NA TEMPERATURA CERTA 🥤", "GELADO POR HORAS, QUENTE TAMBÉM ☕", "COMPANHEIRA PARA TODO LUGAR 🚶"] },
  { key: "copos-utensilios", category: "HOME_KITCHEN_DECOR", keywords: ["copo", "copos", "taca", "tacas", "caneca", "xicara", "jogo de jantar", "prato", "talher", "faqueiro", "faca", "tabua de corte", "jarra", "utensilios", "espatula", "colher", "abridor", "saca rolhas", "coador", "descanso de panela"], headlines: ["MESA POSTA COM ESTILO 🍽️", "DETALHES QUE DEIXAM A COZINHA LINDA ✨", "PRATICIDADE PARA O DIA A DIA 🍴", "PARA RECEBER BEM QUEM VOCÊ AMA 🥂"] },
  { key: "limpeza", category: "HOME_KITCHEN_DECOR", keywords: ["limpador", "detergente", "desinfetante", "lysoform", "ype", "veja", "finish", "percarbonato", "tira manchas", "esponja", "pano de limpeza", "rodo", "vassoura", "mop", "balde", "agua sanitaria", "lava loucas"], headlines: ["CASA LIMPA SEM ESFORÇO 🧽", "LIMPEZA QUE DÁ GOSTO DE VER ✨", "BRILHO EM CADA CANTINHO 🧼", "MENOS TRABALHO, MAIS RESULTADO 🙌"] },
  { key: "lavanderia", category: "HOME_KITCHEN_DECOR", keywords: ["lava roupas", "sabao em po", "sabao liquido", "amaciante", "omo", "downy", "tira manchas de roupa", "varal", "cesto de roupa", "tabua de passar", "ferro de passar", "vaporizador"], headlines: ["ROUPA LIMPINHA E CHEIROSA 👕", "LAVANDERIA EM ORDEM SEM ESFORÇO 🧺", "CUIDADO QUE AS SUAS ROUPAS MERECEM ✨"] },
  { key: "cama-banho", category: "HOME_KITCHEN_DECOR", keywords: ["lencol", "jogo de cama", "edredom", "cobertor", "manta", "colcha", "travesseiro", "fronha", "toalha de banho", "jogo de toalhas", "roupao", "capa de colchao", "protetor de colchao"], headlines: ["NOITES MAIS CONFORTÁVEIS 😴", "SEU QUARTO DIGNO DE HOTEL ✨", "ACONCHEGO PARA DORMIR MELHOR 🛏️", "MACIEZ QUE ABRAÇA 💤"] },
  { key: "decoracao", category: "HOME_KITCHEN_DECOR", keywords: ["quadro", "espelho", "vaso", "planta artificial", "flores artificiais", "luminaria", "abajur", "cortina", "tapete", "almofada", "porta retrato", "relogio de parede", "adesivo de parede", "papel de parede", "letreiro", "painel decorativo", "enfeite", "apliques"], headlines: ["SUA CASA COM CARA DE REVISTA ✨", "DETALHES QUE TRANSFORMAM O AMBIENTE 🏡", "DECORAÇÃO QUE DÁ VONTADE DE FICAR EM CASA 💛", "ESTILO PARA CADA CANTINHO 🖼️"] },
  { key: "iluminacao", category: "HOME_KITCHEN_DECOR", keywords: ["lampada", "lampada led", "fita led", "refletor", "pendente", "spot", "arandela", "cordao de luz", "pisca pisca", "luminaria de mesa"], headlines: ["ILUMINAÇÃO QUE MUDA O AMBIENTE 💡", "ECONOMIA E LUZ NA MEDIDA CERTA 💡", "CLIMA ACONCHEGANTE EM UM CLIQUE ✨"] },
  { key: "moveis", category: "HOME_KITCHEN_DECOR", keywords: ["cadeira", "mesa", "rack", "estante", "armario", "guarda roupa", "comoda", "sofa", "poltrona", "banqueta", "puff", "escrivaninha", "mesa de cabeceira", "cabeceira", "painel tv"], headlines: ["CONFORTO E ESTILO PARA A SUA CASA 🛋️", "O MÓVEL QUE FALTAVA NO AMBIENTE 🏡", "MAIS ESPAÇO E ORGANIZAÇÃO ✨"] },
  { key: "festa", category: "HOME_KITCHEN_DECOR", keywords: ["balao", "baloes", "kit festa", "topo de bolo", "forminha", "vela de aniversario", "painel de festa", "toalha de mesa", "banner", "lembrancinha", "personalizado"], headlines: ["FESTA LINDA SEM GASTAR MUITO 🎉", "DECORAÇÃO QUE ENCANTA OS CONVIDADOS 🎈", "TUDO PRONTO PARA COMEMORAR 🥳"] },
  { key: "ferramentas", category: "HOME_KITCHEN_DECOR", keywords: ["parafusadeira", "furadeira", "motosserra", "serra tico tico", "esmerilhadeira", "lixadeira", "chave de fenda", "jogo de chaves", "kit ferramentas", "maleta de ferramentas", "alicate", "martelo", "trena", "nivel a laser", "soprador", "lavadora de alta pressao", "compressor", "trincha"], headlines: ["FERRAMENTA PODEROSA PARA SEUS PROJETOS ⚡", "FAÇA VOCÊ MESMO COM QUALIDADE 🔧", "O PARCEIRO DE TODA REFORMA 🛠️", "SERVIÇO PROFISSIONAL EM CASA 🔩"] },
  { key: "jardim", category: "HOME_KITCHEN_DECOR", keywords: ["mangueira", "regador", "vaso de planta", "terra adubada", "adubo", "sementes", "tesoura de poda", "cortador de grama", "jardim"], headlines: ["JARDIM LINDO E CHEIO DE VIDA 🌱", "VERDE QUE ALEGRA A CASA 🌿", "CUIDE DAS SUAS PLANTAS COM CARINHO 🪴"] },
  { key: "eletrodomestico-grande", category: "HOME_KITCHEN_DECOR", keywords: ["geladeira", "fogao", "cooktop", "lava e seca", "lavadora", "maquina de lavar", "lava loucas eletrica", "freezer", "adega", "coifa", "depurador", "bebedouro eletrico"], headlines: ["UPGRADE DE RESPEITO PARA A SUA CASA 🏡", "PRATICIDADE QUE ECONOMIZA SEU TEMPO ⏱️", "INVESTIMENTO QUE VALE CADA CENTAVO 💰"] },
  { key: "aspirador", category: "HOME_KITCHEN_DECOR", keywords: ["aspirador", "aspirador de po", "robo aspirador", "aspirador vertical", "extratora", "vassoura eletrica"], headlines: ["CASA LIMPA SEM ESFORÇO 🧹", "ADEUS PÓ E SUJEIRA 🙌", "LIMPEZA PRÁTICA EM MINUTOS ⚡"] },
  { key: "climatizacao", category: "HOME_KITCHEN_DECOR", keywords: ["ventilador", "ar condicionado", "climatizador", "aquecedor", "circulador de ar", "ventilador de mesa", "ventilador de teto"], headlines: ["FRESCOR NOS DIAS QUENTES 🌬️", "CONFORTO TÉRMICO EM QUALQUER ESTAÇÃO ❄️", "CASA FRESQUINHA NO VERÃO 🌬️"] },
  { key: "filtro-agua", category: "HOME_KITCHEN_DECOR", keywords: ["filtro de agua", "refil", "purificador de agua", "filtro", "dispenser de agua", "bomba de agua"], headlines: ["PRATICIDADE NA ÁGUA DE CASA 💧", "ÁGUA FILTRADA COM PRATICIDADE 💧", "PRATICIDADE E ÁGUA DE QUALIDADE 💧"] },
  { key: "borrifador", category: "HOME_KITCHEN_DECOR", keywords: ["spray azeite", "spray de azeite", "porta oleo", "borrifador", "spray de oleo", "pulverizador", "dispenser", "dosador", "saboneteira", "porta detergente", "porta papel toalha"], headlines: ["PRATICIDADE NO DIA A DIA DA CASA ✨", "PEQUENO ITEM, GRANDE DIFERENÇA 🙌", "ECONOMIA E ORGANIZAÇÃO NA PIA 💧"] },

  // ---------- Eletrônicos ----------
  { key: "fone", category: "ELECTRONICS", keywords: ["fone", "fone de ouvido", "fone bluetooth", "headphone", "headset", "earbuds", "airpods", "fone sem fio", "fone tws"], headlines: ["SOM DE QUALIDADE EM QUALQUER LUGAR 🎧", "SUA PLAYLIST NUNCA FOI TÃO BOA 🎶", "LIBERDADE SEM FIOS 🎧", "MERGULHE NA SUA MÚSICA 🎵"] },
  { key: "caixa-som", category: "ELECTRONICS", keywords: ["caixa de som", "caixinha de som", "som", "jbl", "soundbar", "caixa bluetooth", "caixa amplificada", "amplificada", "speaker", "soundcore"], headlines: ["SOM QUE ANIMA QUALQUER ROLÊ 🔊", "GRAVE POTENTE PARA A SUA FESTA 🎉", "LEVE A MÚSICA PARA ONDE FOR 🎶"] },
  { key: "smartwatch", category: "ELECTRONICS", keywords: ["relogio smartwatch", "relogio inteligente smartwatch", "smartwatch", "smart watch", "relogio inteligente", "smartband", "pulseira inteligente", "mi band", "apple watch", "galaxy watch", "iwo"], headlines: ["TECNOLOGIA NO SEU PULSO ⌚", "SAÚDE E NOTIFICAÇÕES NA PALMA DA MÃO ⌚", "ESTILO E PRATICIDADE NO DIA A DIA ⌚", "SEU TREINO MONITORADO 24H 💪"] },
  { key: "pulseira-relogio", category: "ELECTRONICS", keywords: ["pulseira para smartwatch", "pulseira de relogio", "pulseira para apple watch", "pulseira"], headlines: ["NOVO VISUAL PARA O SEU RELÓGIO ⌚", "COMBINE COM CADA LOOK ✨", "CONFORTO E ESTILO NO PULSO ⌚"] },
  { key: "carregador", category: "ELECTRONICS", keywords: ["carregador", "fonte de carregador", "carregador turbo", "carregador portatil", "power bank", "powerbank", "carregador por inducao", "carregador sem fio", "fonte usb", "fonte"], headlines: ["BATERIA CHEIA EM MINUTOS 🔋", "NUNCA MAIS FIQUE SEM BATERIA ⚡", "CARGA RÁPIDA PARA A CORRERIA ⚡"] },
  { key: "cabo", category: "ELECTRONICS", keywords: ["cabo usb", "cabo tipo c", "cabo lightning", "cabo hdmi", "cabo", "adaptador", "hub usb", "extensao", "filtro de linha"], headlines: ["CONEXÃO RÁPIDA E RESISTENTE 🔌", "O CABO QUE NÃO TE DEIXA NA MÃO ⚡", "ITEM ESSENCIAL PARA O DIA A DIA 🔌"] },
  { key: "celular", category: "ELECTRONICS", keywords: ["smartphone", "celular", "iphone", "galaxy", "xiaomi", "redmi", "motorola", "poco"], headlines: ["TECNOLOGIA DE PONTA NA SUA MÃO 📱", "UPGRADE QUE VOCÊ MERECE 📱", "FOTOS LINDAS E BATERIA DE SOBRA 📸"] },
  { key: "acessorio-celular", category: "ELECTRONICS", keywords: ["capinha", "capa para celular", "pelicula", "pelicula de vidro", "suporte de celular", "suporte veicular", "pop socket", "anel de celular", "tripe", "pau de selfie", "estabilizador"], headlines: ["PROTEÇÃO E ESTILO PARA O SEU CELULAR 📱", "SEU CELULAR MAIS PROTEGIDO 🛡️", "PRATICIDADE NA PALMA DA MÃO 📱"] },
  { key: "smart-home", category: "ELECTRONICS", keywords: ["echo dot", "alexa", "echo", "smart plug", "tomada inteligente", "lampada inteligente", "smart", "google nest", "fire tv", "roku", "chromecast", "tv box", "camera de seguranca", "camera wifi", "camera ip", "fechadura digital", "campainha"], headlines: ["SUA CASA MAIS INTELIGENTE 🏠", "TECNOLOGIA QUE FACILITA A ROTINA ⚡", "CONTROLE TUDO PELA VOZ 🗣️", "SEGURANÇA E PRATICIDADE NA PALMA DA MÃO 📲"] },
  { key: "tv-projetor", category: "ELECTRONICS", keywords: ["smart tv", "televisao", "tv", "projetor", "monitor", "tela de projecao"], headlines: ["CINEMA NA SALA DE CASA 🎬", "MARATONA DE SÉRIES COM QUALIDADE 🍿", "IMAGEM QUE IMPRESSIONA 📺"] },
  { key: "informatica", category: "ELECTRONICS", keywords: ["notebook", "ssd", "hd externo", "pen drive", "pendrive", "cartao de memoria", "mouse", "teclado", "mousepad", "webcam", "roteador", "repetidor", "headset gamer", "impressora", "tablet", "ipad", "kindle", "leitor digital"], headlines: ["MAIS PRODUTIVIDADE NO SEU DIA 💻", "TECNOLOGIA QUE TRABALHA POR VOCÊ ⚡", "SETUP COMPLETO SEM GASTAR MUITO 🖥️"] },
  { key: "games", category: "ELECTRONICS", keywords: ["controle", "joystick", "gamepad", "console", "playstation", "xbox", "nintendo", "cadeira gamer", "jogo ps5", "jogo"], headlines: ["NÍVEL MÁXIMO DE DIVERSÃO 🎮", "PARTIDAS MAIS ÉPICAS 🕹️", "O UPGRADE DO SEU SETUP GAMER 🎮"] },
  { key: "pilhas", category: "ELECTRONICS", keywords: ["pilha", "pilhas", "bateria recarregavel", "duracell", "bateria"], headlines: ["ENERGIA QUE DURA MUITO MAIS 🔋", "NUNCA MAIS FIQUE SEM PILHA 🔋", "ESTOQUE GARANTIDO COM ECONOMIA ⚡"] },
  { key: "camera", category: "ELECTRONICS", keywords: ["camera", "camera instantanea", "gopro", "camera digital", "microfone", "microfone de lapela", "ring light", "drone"], headlines: ["REGISTRE OS MELHORES MOMENTOS 📸", "CONTEÚDO DE QUALIDADE PROFISSIONAL 🎥", "SUA CRIATIVIDADE SEM LIMITES 🎬"] },
  { key: "eletronico-carro", category: "ELECTRONICS", keywords: ["som automotivo", "central multimidia", "camera de re", "aspirador automotivo", "carregador veicular", "transmissor fm", "sensor de estacionamento", "calibrador de pneus"], headlines: ["SEU CARRO MAIS COMPLETO 🚗", "TECNOLOGIA PARA CURTIR A ESTRADA 🛣️", "PRATICIDADE AO VOLANTE 🚗"] },
  { key: "oculos", category: "FASHION", keywords: ["oculos de sol", "oculos", "armacao de oculos"], headlines: ["ESTILO E PROTEÇÃO PARA OS OLHOS 😎", "O ACESSÓRIO QUE MUDA O LOOK 😎", "ATITUDE EM CADA OLHAR 🕶️"] },

  // ---------- Infantil e Baby ----------
  { key: "fralda", category: "KIDS_BABY", keywords: ["fralda", "fraldas", "huggies", "pampers", "turma da monica baby", "fralda de pano", "fralda calça", "fralda calca"], headlines: ["BUMBUM SEQUINHO A NOITE TODA 👶", "CONFORTO PARA O BEBÊ, ECONOMIA PARA VOCÊ 💙", "ESTOQUE DE FRALDA COM PREÇO BOM 🛒"] },
  { key: "lenco-umedecido", category: "KIDS_BABY", keywords: ["lenco umedecido", "lencos umedecidos", "toalhinha umedecida"], headlines: ["PRATICIDADE NA TROCA DO BEBÊ 👶", "CUIDADO DELICADO NO DIA A DIA 💙", "ITEM QUE NÃO PODE FALTAR NA BOLSA 👜"] },
  { key: "higiene-bebe", category: "KIDS_BABY", keywords: ["sabonete liquido bebe", "sabonete bebe", "mustela", "johnsons baby", "shampoo infantil", "sabonete infantil", "pomada para assaduras", "hipoglos", "banheira", "termometro de banho", "kit higiene bebe"], headlines: ["CARINHO NA HORA DO BANHO 🛁", "CUIDADO SUAVE PARA O BEBÊ 💙", "CUIDADO SUAVE NA HORA DO BANHO 👶"] },
  { key: "alimentacao-bebe", category: "KIDS_BABY", keywords: ["mamadeira", "chupeta", "bico", "copo de transicao", "pratinho infantil", "babador", "esterilizador", "aquecedor de mamadeira", "bomba tira leite", "cadeira de alimentacao", "mordedor infantil"], headlines: ["HORA DA PAPINHA SEM BAGUNÇA 🍼", "PRATICIDADE PARA A FAMÍLIA DO BEBÊ 💙", "CUIDADO EM CADA REFEIÇÃO 🍼"] },
  { key: "mochila-escolar", category: "KIDS_BABY", keywords: ["mochila escolar", "mochila infantil", "mochila de rodinha", "lancheira", "estojo", "kit escolar", "material escolar", "mochila"], headlines: ["VOLTA ÀS AULAS COM ESTILO 🎒", "A MOCHILA QUE A CRIANÇADA AMA 🎒", "RESISTENTE PARA O DIA A DIA 🎒", "ORGANIZAÇÃO PARA A ESCOLA 📚"] },
  { key: "brinquedo", category: "KIDS_BABY", keywords: ["brinquedo", "boneca", "boneco", "carrinho de brinquedo", "hot wheels", "lego", "blocos de montar", "quebra cabeca", "jogo de tabuleiro", "massinha", "slime", "squishy", "fidget", "pista", "fisher price", "playmobil", "labirinto"], headlines: ["DIVERSÃO GARANTIDA PARA A CRIANÇADA 🧸", "PRESENTE QUE FAZ OS OLHOS BRILHAREM 🎁", "HORAS DE BRINCADEIRA LONGE DAS TELAS 🎈", "APRENDER BRINCANDO É MUITO MELHOR 🧩"] },
  { key: "pelucia", category: "KIDS_BABY", keywords: ["pelucia", "ursinho", "urso de pelucia", "naninha"], headlines: ["ABRAÇO FOFINHO GARANTIDO 🧸", "COMPANHEIRO DE TODAS AS NOITES 💤", "PRESENTE QUE CONQUISTA NA HORA 🧸"] },
  { key: "bicicleta-infantil", category: "KIDS_BABY", keywords: ["bicicleta infantil", "triciclo", "patinete", "velotrol", "bicicleta sem pedal", "balance bike", "skate infantil", "patins", "bicicleta"], headlines: ["AVENTURA SOBRE RODAS 🚲", "DIVERSÃO AO AR LIVRE GARANTIDA ☀️", "ENERGIA DA CRIANÇADA BEM GASTA 🛴"] },
  { key: "carrinho-bebe", category: "KIDS_BABY", keywords: ["carrinho de bebe", "bebe conforto", "cadeirinha para carro", "assento elevacao", "canguru", "sling", "travel system", "carrinho"], headlines: ["PASSEIOS SEGUROS E CONFORTÁVEIS 👶", "SEGURANÇA PARA O SEU BEBÊ 💙", "PRATICIDADE PARA SAIR COM O BEBÊ 🚼"] },
  { key: "quarto-bebe", category: "KIDS_BABY", keywords: ["berco", "mini berco", "kit berco", "baba eletronica", "tapete de atividades", "tapete infantil", "tapete eva", "mobile", "ninho redutor", "saida de maternidade", "saco de dormir", "grade de protecao", "portao de seguranca"], headlines: ["QUARTINHO SEGURO E ACONCHEGANTE 👶", "CONFORTO PARA O SONINHO DO BEBÊ 💤", "TRANQUILIDADE PARA OS PAIS 💙"] },
  { key: "roupa-bebe", category: "KIDS_BABY", keywords: ["body de bebe", "body infantil", "macacao", "macacao bebe", "conjunto infantil", "kit body", "pijama infantil", "vestido infantil", "sapatinho", "meia de bebe", "touca de bebe", "manta de bebe"], headlines: ["FOFURA EM FORMA DE ROUPA 👶", "CONFORTO PARA OS PEQUENOS 💙", "LOOK LINDO PARA O BEBÊ ✨"] },
  { key: "livro-infantil", category: "KIDS_BABY", keywords: ["livro infantil", "livro de colorir", "livro sensorial", "gibi", "livro"], headlines: ["HISTÓRIAS QUE ENCANTAM 📚", "INCENTIVE A LEITURA DESDE CEDO 📖", "MOMENTO ESPECIAL EM FAMÍLIA 📚"] },
  { key: "piscina-praia-infantil", category: "KIDS_BABY", keywords: ["piscina inflavel", "boia", "colete salva vidas", "baldinho de praia", "piscina de bolinhas"], headlines: ["VERÃO DE DIVERSÃO GARANTIDA ☀️", "BRINCADEIRA REFRESCANTE 💦", "ALEGRIA DA CRIANÇADA NO CALOR 🌊"] },

  // ---------- Moda ----------
  { key: "tenis-corrida", category: "FASHION", keywords: ["tenis de corrida", "tenis running", "tenis para corrida", "tenis esportivo", "tenis de academia", "tenis para academia"], headlines: ["PERFORMANCE EM CADA PASSADA 🏃", "CONFORTO PARA BATER SUAS METAS 👟", "CORRA MAIS LONGE COM ESTILO 🏃"], feminine: ["PARA ELA CORRER COM CONFORTO 🏃"], masculine: ["PARA ELE CORRER COM CONFORTO 🏃"] },
  { key: "tenis", category: "FASHION", keywords: ["tenis", "sneaker", "sapatenis", "tenis casual", "all star", "nike", "adidas", "olympikus", "mizuno", "fila", "vans", "puma"], headlines: ["CONFORTO QUE VAI COM TUDO 👟", "O TÊNIS QUE FALTAVA NO SEU LOOK 👟", "ESTILO DA CABEÇA AOS PÉS 🔥", "PISE COM ESTILO 👟"], feminine: ["O TÊNIS QUE VAI COM TODOS OS LOOKS DELA 👟"], masculine: ["O TÊNIS QUE VAI COM TODOS OS LOOKS DELE 👟"] },
  { key: "calcado", category: "FASHION", keywords: ["sapato", "sandalia", "rasteirinha", "tamanco", "bota", "coturno", "scarpin", "mocassim", "chinelo", "havaianas", "slide", "papete", "sapatilha", "crocs", "babuche"], headlines: ["CONFORTO PARA OS SEUS PÉS 👡", "O PAR CERTO PARA CADA OCASIÃO ✨", "PÉS LINDOS E CONFORTÁVEIS 👠"], feminine: ["O PAR QUE ELA VAI AMAR 👡"], masculine: ["O PAR CERTO PARA ELE 👞"] },
  { key: "bolsa", category: "FASHION", keywords: ["bolsa", "bolsa feminina", "bolsa transversal", "bolsa de ombro", "clutch", "carteira", "porta cartoes", "pochete", "bolsa tote", "shoulder bag"], headlines: ["O ACESSÓRIO QUE COMPLETA O LOOK 👜", "ESTILO E PRATICIDADE NO DIA A DIA 👜", "CABE TUDO E COMBINA COM TUDO ✨", "ELEGÂNCIA EM CADA DETALHE 👛"], feminine: ["A BOLSA QUE ELA VAI AMAR 👜"], masculine: ["PRATICIDADE E ESTILO PARA ELE 👝"] },
  { key: "mochila", category: "FASHION", keywords: ["mochila notebook", "mochila executiva", "mochila de viagem", "mochila feminina", "mochila masculina", "mochila antifurto"], headlines: ["PRATICIDADE PARA A SUA ROTINA 🎒", "LEVE TUDO COM ESTILO 🎒", "RESISTENTE PARA O DIA A DIA ✨"] },
  { key: "mala", category: "FASHION", keywords: ["mala", "mala de viagem", "mala de bordo", "kit malas", "mala de rodinha", "frasqueira"], headlines: ["SUA PRÓXIMA VIAGEM COMEÇA AQUI ✈️", "VIAJE COM ESTILO E ORGANIZAÇÃO 🧳", "PRATICIDADE DO EMBARQUE AO DESTINO 🌎"] },
  { key: "camiseta", category: "FASHION", keywords: ["camiseta", "camisetas", "t shirt", "tshirt", "camiseta basica", "regata", "baby look", "cropped", "blusa", "blusinha", "camisa polo", "polo"], headlines: ["BÁSICO QUE NUNCA SAI DE MODA 👕", "CONFORTO PARA O DIA A DIA 👕", "COMBINA COM TUDO ✨", "O CORINGA DO SEU GUARDA-ROUPA 👚"], feminine: ["O BÁSICO QUE TODA MULHER AMA 👚"], masculine: ["O BÁSICO QUE TODO HOMEM PRECISA 👕"] },
  { key: "camisa", category: "FASHION", keywords: ["camisa social", "camisa", "camisa de linho", "camisa manga longa"], headlines: ["ELEGÂNCIA PARA QUALQUER OCASIÃO 👔", "VISUAL ALINHADO SEM ESFORÇO 👔", "ESTILO QUE IMPRESSIONA ✨"], feminine: ["ELEGÂNCIA FEMININA PARA QUALQUER OCASIÃO 👚"], masculine: ["VISUAL MASCULINO ALINHADO 👔"] },
  { key: "calca", category: "FASHION", keywords: ["calca", "calca jeans", "calca legging", "legging", "calca alfaiataria", "calca cargo", "calca wide leg", "jogger", "bermuda", "short", "saia"], headlines: ["CAIMENTO PERFEITO, CONFORTO TOTAL 👖", "A PEÇA QUE VALORIZA SEU LOOK ✨", "ESTILO PARA TODOS OS DIAS 👖"], feminine: ["CAIMENTO QUE VALORIZA A SILHUETA DELA 👖"], masculine: ["CAIMENTO PERFEITO PARA ELE 👖"] },
  { key: "vestido", category: "FASHION", keywords: ["vestido", "vestido longo", "vestido midi", "macacao feminino", "macaquinho", "conjunto feminino"], headlines: ["LOOK PRONTO PARA ARRASAR 👗", "ELEGÂNCIA SEM ESFORÇO ✨", "A PEÇA QUE ARRASA EM QUALQUER OCASIÃO 👗"] },
  { key: "agasalho", category: "FASHION", keywords: ["moletom", "jaqueta", "casaco", "blazer", "corta vento", "sueter", "cardigan", "colete", "jaqueta jeans", "jaqueta puffer"], headlines: ["QUENTINHO COM ESTILO 🧥", "O FRIO CHEGOU, O ESTILO TAMBÉM ❄️", "A PEÇA QUE FAZ O LOOK 🧥"], feminine: ["ELA AQUECIDA E CHEIA DE ESTILO 🧥"], masculine: ["ELE AQUECIDO E CHEIO DE ESTILO 🧥"] },
  { key: "moda-intima", category: "FASHION", keywords: ["calcinha", "calcinhas", "cueca", "cuecas", "sutia", "lingerie", "kit calcinha", "kit cueca", "body feminino", "camisola", "pijama", "meia", "meias", "meia calca"], headlines: ["CONFORTO QUE COMEÇA POR DENTRO ✨", "KIT COMPLETO COM PREÇO DE OPORTUNIDADE 🛒", "MACIEZ PARA O DIA A DIA 💕"], feminine: ["CONFORTO E DELICADEZA PARA ELA 💕"], masculine: ["CONFORTO DE VERDADE PARA ELE 🩲"] },
  { key: "moda-praia", category: "FASHION", keywords: ["biquini", "maio", "sunga", "saida de praia", "canga", "bermuda de praia", "short de praia"], headlines: ["O VERÃO COMEÇA NO SEU LOOK ☀️", "BRILHE NA PRAIA E NA PISCINA 🌊", "ESTILO DEBAIXO DO SOL 🏖️"] },
  { key: "acessorio-moda", category: "FASHION", keywords: ["cinto", "bone", "chapeu", "gorro", "cachecol", "lenco", "guarda chuva", "sombrinha", "relogio", "relogio masculino", "relogio feminino"], headlines: ["O DETALHE QUE MUDA O LOOK ✨", "ACESSÓRIO QUE COMBINA COM VOCÊ 😎", "ESTILO NOS DETALHES 🔥"], feminine: ["O ACESSÓRIO QUE COMPLETA O LOOK DELA ✨"], masculine: ["O ACESSÓRIO QUE COMPLETA O LOOK DELE ⌚"] },
  { key: "joias", category: "FASHION", keywords: ["colar", "brinco", "anel", "pulseira feminina", "corrente", "pingente", "berloque", "semijoia", "joia", "prata 925", "folheado"], headlines: ["BRILHO QUE ENCANTA ✨", "O PRESENTE PERFEITO 💍", "DELICADEZA EM CADA DETALHE 💎"], feminine: ["O BRILHO QUE ELA MERECE 💎"], masculine: ["ESTILO MASCULINO NOS DETALHES ⛓️"] },
  { key: "acessorio-cabelo", category: "FASHION", keywords: ["piranha de cabelo", "presilha", "tiara", "scrunchie", "elastico de cabelo", "laco de cabelo", "faixa de cabelo"], headlines: ["PENTEADO LINDO EM SEGUNDOS 🎀", "O TOQUE FOFO DO SEU VISUAL 🎀", "PRATICIDADE PARA OS DIAS CORRIDOS ✨"] },
  { key: "esporte-moda", category: "FASHION", keywords: ["conjunto fitness", "top fitness", "top", "short fitness", "roupa de academia", "camiseta dry fit", "dry fit", "raquete", "bola de futebol", "camisa de time", "chuteira", "luva de goleiro"], headlines: ["TREINE COM ESTILO E CONFORTO 🏋️", "LOOK FITNESS QUE MOTIVA 💪", "HORA DE SUAR A CAMISA COM ESTILO 🔥"] },

  // ---------- Pets ----------
  { key: "racao-cao", category: "PETS", keywords: ["racao para caes", "racao para cachorro", "racao canina", "racao cao", "racao dog", "pedigree", "golden", "premier", "quatree", "special dog", "racao"], headlines: ["NUTRIÇÃO DE QUALIDADE PARA SEU PET 🐶", "CARINHO QUE COMEÇA NO POTINHO 🐾", "SEU MELHOR AMIGO MERECE O MELHOR 🐕", "RAÇÃO BOA COM PREÇO MELHOR AINDA 🛒"] },
  { key: "racao-gato", category: "PETS", keywords: ["racao para gatos", "racao felina", "racao gato", "whiskas", "gran plus gatos", "sache", "sache para gatos", "felix"], headlines: ["O PETISCO QUE O GATO AMA 🐱", "NUTRIÇÃO COMPLETA PARA O SEU FELINO 🐾", "GATO FELIZ, DONO FELIZ 😺"] },
  { key: "petisco", category: "PETS", keywords: ["petisco", "bifinho", "snack para cachorro", "snack", "churu", "osso para cachorro", "biscoito para cachorro", "palito", "dental stick"], headlines: ["A RECOMPENSA QUE SEU PET MERECE 🦴", "O MIMO PREFERIDO DO SEU PET 🐶", "PETISCO DE RESPEITO PARA O SEU AMIGO 🐾"] },
  { key: "areia-gato", category: "PETS", keywords: ["areia para gatos", "areia sanitaria", "areia", "pipicat", "granulado higienico", "caixa de areia", "sanitario para gatos"], headlines: ["ADEUS CHEIRO RUIM 🐱", "HIGIENE E PRATICIDADE PARA O SEU GATO 🐾", "CASA LIMPA E GATO FELIZ 😺"] },
  { key: "tapete-higienico", category: "PETS", keywords: ["tapete higienico", "tapete sanitario", "fralda para cachorro", "jornal pet", "jornal"], headlines: ["MAIS HIGIENE PARA A CASA 🐶", "PRATICIDADE NO DIA A DIA DO PET 🐾", "ABSORÇÃO QUE FAZ DIFERENÇA ✨"] },
  { key: "brinquedo-pet", category: "PETS", keywords: ["brinquedo para cachorro", "brinquedo para gato", "mordedor", "bolinha", "bola para cachorro", "corda para cachorro", "kong", "varinha para gato", "brinquedo pet", "brinquedo interativo"], headlines: ["DIVERSÃO GARANTIDA PARA O SEU PET 🐶", "ADEUS TÉDIO, OLÁ BRINCADEIRA 🎾", "SEU PET MAIS FELIZ E ATIVO 🐾", "O BRINQUEDO PREFERIDO DA CASA 🦴"] },
  { key: "cama-pet", category: "PETS", keywords: ["cama pet", "caminha", "cama para cachorro", "cama para gato", "almofada pet", "casinha", "toca para gato", "manta pet", "cama"], headlines: ["SONINHO GOSTOSO PARA O SEU PET 💤", "O CONFORTO QUE SEU PET MERECE 🐾", "O CANTINHO PREFERIDO DO SEU AMIGO 🐶"] },
  { key: "arranhador", category: "PETS", keywords: ["arranhador", "arranhador para gatos", "torre para gatos", "prateleira para gatos", "nicho para gatos"], headlines: ["ADEUS SOFÁ ARRANHADO 😺", "DIVERSÃO GARANTIDA PARA O SEU GATO 🐱", "O PARQUE DE DIVERSÕES DO SEU GATO 🐾"] },
  { key: "comedouro", category: "PETS", keywords: ["comedouro", "bebedouro", "fonte para gatos", "fonte bebedouro", "comedouro automatico", "porta racao", "pote pet"], headlines: ["HIDRATAÇÃO E REFEIÇÃO NA MEDIDA CERTA 💧", "PRATICIDADE NA HORA DE ALIMENTAR 🐾", "MAIS PRATICIDADE PARA O SEU PET 🐶"] },
  { key: "antipulgas", category: "PETS", keywords: ["antipulgas", "nexgard", "simparic", "bravecto", "credeli", "coleira antipulgas", "vermifugo", "frontline", "seresto", "zoetis", "virbac"], headlines: ["PRATICIDADE NO CUIDADO DO SEU PET 🐶", "CUIDADO EM DIA COM O SEU PET 🐾", "TRANQUILIDADE PARA VOCÊ E SEU PET 💚"] },
  { key: "passeio-pet", category: "PETS", keywords: ["coleira", "guia", "peitoral", "caixa de transporte", "bolsa de transporte", "mochila pet", "focinheira", "guia retratil"], headlines: ["PASSEIOS SEGUROS E DIVERTIDOS 🐕", "CONFORTO E SEGURANÇA NA RUA 🐾", "HORA DO PASSEIO COM SEGURANÇA 🦮"] },
  { key: "higiene-pet", category: "PETS", keywords: ["shampoo pet", "shampoo para cachorro", "escova pet", "escova para cachorro", "rasqueadeira", "cortador de unha pet", "tira pelos", "luva tira pelos", "perfume pet", "lenco umedecido pet"], headlines: ["PET LIMPINHO E CHEIROSO 🛁", "BANHO E TOSA EM CASA 🐶", "PET CHEIROSO E BEM CUIDADO ✨"] },
  { key: "roupa-pet", category: "PETS", keywords: ["roupa pet", "roupa para cachorro", "roupinha pet", "capa de chuva pet", "fantasia pet"], headlines: ["SEU PET NA MODA 🐶", "QUENTINHO E ESTILOSO 🐾", "FOFURA QUE NINGUÉM RESISTE 😍"] },
  { key: "aquario-passaro", category: "PETS", keywords: ["aquario", "racao para peixes", "gaiola", "racao para passaros", "alpiste", "viveiro", "hamster"], headlines: ["CUIDADO COMPLETO PARA O SEU BICHINHO 🐾", "AMBIENTE PERFEITO PARA O SEU PET 🐠", "SEU PET BEM CUIDADO TODO DIA 🐦"] },

  // ---------- Complementos (tipos que mais faltavam nos títulos reais, 10/2026) ----------
  { key: "cappuccino", category: "FOOD_BEVERAGES", keywords: ["cappuccino", "capsula de cappuccino", "latte", "chocolate quente"], headlines: ["CREMOSO DO JEITO QUE VOCÊ AMA ☕", "CAFETERIA EM CASA ☕", "UM ABRAÇO EM FORMA DE BEBIDA ☕"] },
  { key: "destilado", category: "FOOD_BEVERAGES", keywords: ["whiskey", "bourbon", "aperitivo", "aperol", "campari", "jagermeister", "conhaque", "saque"], headlines: ["DRINK DE RESPEITO PARA O FIM DE SEMANA 🥃", "PARA BRINDAR EM GRANDE ESTILO 🥂", "O RÓTULO QUE FALTAVA NO SEU BAR 🥃"] },
  { key: "barrinha", category: "FOOD_BEVERAGES", keywords: ["barrinha", "barra de cereal", "barrinhas", "goiabada", "pacoquinha", "pastilha"], headlines: ["LANCHINHO PRÁTICO PARA A BOLSA 😋", "DOÇURA NA MEDIDA CERTA 🍫", "ENERGIA RÁPIDA NO MEIO DA TARDE ⚡"] },
  { key: "xarope-adocante", category: "FOOD_BEVERAGES", keywords: ["xarope", "adocante", "acucar", "sal marinho", "sal", "vinagre", "oleo de soja", "oleo"], headlines: ["ESSENCIAL NA SUA COZINHA 🛒", "SABOR E ECONOMIA PARA A DESPENSA 🛒", "O BÁSICO QUE NÃO PODE FALTAR 🍽️"] },
  { key: "bb-cream", category: "BEAUTY", keywords: ["bb cream", "cc cream", "base com protetor", "maquiagem infantil", "kit de maquiagem", "bb glow"], headlines: ["MAKE LEVE E PRÁTICA ✨", "MAKE LEVE COM COBERTURA DE VERDADE 💄", "PRATICIDADE QUE CABE NA BOLSA 💖"] },
  { key: "algodao-hastes", category: "BEAUTY", keywords: ["algodao", "hastes flexiveis", "cotonete", "discos de algodao", "lenco demaquilante"], headlines: ["ITEM BÁSICO QUE NÃO PODE FALTAR ✨", "CUIDADO DELICADO NO DIA A DIA 🌸", "ESTOQUE COM PREÇO DE OPORTUNIDADE 🛒"] },
  { key: "oleo-corporal", category: "BEAUTY", keywords: ["bio oil", "oleo corporal", "oleo extraordinario", "oleo de rosa mosqueta", "baume", "cicaplast", "oleo multifuncional"], headlines: ["O MULTIUSO DO NÉCESSAIRE ✨", "O MULTIUSO QUE SUA PELE AMA 💧", "UM CUIDADO A MAIS NA ROTINA 🌿"] },
  { key: "escova-massageadora", category: "BEAUTY", keywords: ["escova massageadora", "massageador capilar", "gua sha", "rolo de jade", "massageador facial"], headlines: ["RITUAL DE SPA EM CASA 💆", "SEU MOMENTO DE AUTOCUIDADO ✨", "AUTOCUIDADO QUE FAZ BEM 🌿"] },
  { key: "papel-toalha", category: "HOME_KITCHEN_DECOR", keywords: ["papel toalha", "pano reutilizavel", "guardanapo", "rolo de papel", "pano multiuso"], headlines: ["PRATICIDADE NA COZINHA TODO DIA 🧻", "ESTOQUE QUE RENDE E ECONOMIZA 🛒", "LIMPEZA RÁPIDA SEM COMPLICAÇÃO ✨"] },
  { key: "controle-pragas", category: "HOME_KITCHEN_DECOR", keywords: ["armadilha", "inseticida", "ratoeira", "repelente", "barata", "cupim", "formiga", "formicida", "cupinicida", "raticida", "mata mosquito", "mata barata"], headlines: ["CASA PROTEGIDA SEM COMPLICAÇÃO 🏠", "CUIDADO EXTRA PARA A SUA CASA 🛡️", "TRANQUILIDADE EM CADA CANTO DA CASA 🏡", "PRÁTICO DE USAR NO DIA A DIA ✅"] },
  { key: "repelente-corporal", category: "HEALTH", keywords: ["repelente corporal", "repelente para bebe", "repelente infantil", "repelente baby", "repelente locao", "repelente spray corporal", "locao repelente"], headlines: ["PRÁTICO PARA LEVAR NA BOLSA 👜", "ITEM CERTO PARA O PASSEIO AO AR LIVRE 🌳", "CUIDADO PRÁTICO PARA TODA A FAMÍLIA 👨‍👩‍👧"] },
  { key: "saco-lixo", category: "HOME_KITCHEN_DECOR", keywords: ["saco de lixo", "sacos para lixo", "saco lixo", "lixeira", "saco para lixo"], headlines: ["CASA LIMPA SEM DRAMA 🗑️", "ESTOQUE GARANTIDO COM ECONOMIA 🛒", "RESISTENTE DE VERDADE 💪"] },
  { key: "pia-banheiro", category: "HOME_KITCHEN_DECOR", keywords: ["rodinho de pia", "chuveiro", "ducha", "torneira", "tapete de banheiro", "kit banheiro", "porta escova", "assento sanitario", "desentupidor"], headlines: ["BANHEIRO E PIA SEMPRE EM ORDEM ✨", "PRATICIDADE NA HORA DA LIMPEZA 🧽", "PEQUENO ITEM, GRANDE DIFERENÇA 🙌"] },
  { key: "tigelas-tabuas", category: "HOME_KITCHEN_DECOR", keywords: ["bowl", "bowls", "tigela", "tigelas", "tabua", "tabua de carne", "assadeira", "forma de bolo", "refratario", "travessa"], headlines: ["PARA COZINHAR E SERVIR COM ESTILO 🍽️", "UTILIDADE QUE TODA COZINHA PRECISA 🍴", "QUALIDADE QUE DURA ANOS ✨"] },
  { key: "blender", category: "HOME_KITCHEN_DECOR", keywords: ["blender", "personal blender", "mini processador", "triturador", "moedor de cafe", "moedor"], headlines: ["SUCOS E VITAMINAS EM SEGUNDOS 🥤", "PRATICIDADE PARA SUCOS E VITAMINAS 🍓", "COMPACTO E POTENTE ⚡"] },
  { key: "luz-festa", category: "ELECTRONICS", keywords: ["strobo", "moving head", "globo de luz", "laser de festa", "maquina de fumaca", "luz de festa", "luz negra"], headlines: ["FESTA COM CARA DE BALADA 🎉", "ILUMINAÇÃO QUE ANIMA A NOITE 💡", "SEU EVENTO MUITO MAIS ANIMADO 🪩"] },
  { key: "acustica-antena", category: "ELECTRONICS", keywords: ["fonte chaveada", "fonte de alimentacao", "espuma acustica", "receptor", "antena digital", "conversor digital", "protetor eletrico", "dispositivo de protecao", "estabilizador de energia", "nobreak", "tela de projecao"], headlines: ["SEU SETUP MUITO MAIS COMPLETO 🔌", "PROTEÇÃO E QUALIDADE PARA SEUS APARELHOS ⚡", "TECNOLOGIA QUE RESOLVE ✨"] },
  { key: "karaoke", category: "ELECTRONICS", keywords: ["karaoke", "microfone sem fio", "boombox", "radio", "vitrola", "toca discos"], headlines: ["SOLTE A VOZ EM CASA 🎤", "DIVERSÃO MUSICAL PARA A FAMÍLIA 🎶", "A FESTA COMEÇA AQUI 🎉"] },
  { key: "jogos-tabuleiro", category: "KIDS_BABY", keywords: ["jogo de cartas", "cartas uno", "uno", "baralho", "jogo de mesa", "board game", "sleeves", "domino", "xadrez", "jogo da memoria", "caiu perdeu", "coup"], headlines: ["DIVERSÃO GARANTIDA EM FAMÍLIA 🎲", "NOITE DE JOGOS COM OS AMIGOS 🃏", "RISADAS GARANTIDAS NA MESA 🎲"] },
  { key: "massinha-arte", category: "KIDS_BABY", keywords: ["massa para modelar", "massinha", "tinta guache", "giz de cera", "kit pintura", "argila", "kit arte"], headlines: ["CRIATIVIDADE SEM LIMITES 🎨", "ARTE E DIVERSÃO PARA A CRIANÇADA ✏️", "HORAS DE ATIVIDADE LONGE DAS TELAS 🖍️"] },
  { key: "figura-acao", category: "KIDS_BABY", keywords: ["figura de acao", "action figure", "boneco articulado", "marvel", "funko", "miniatura", "carrinho de controle remoto", "controle remoto"], headlines: ["O COLECIONÁVEL QUE FALTAVA 🦸", "AVENTURAS ÉPICAS NA BRINCADEIRA 💥", "PRESENTE QUE FAZ SUCESSO 🎁"] },
  { key: "cuidados-bebe-saude", category: "KIDS_BABY", keywords: ["toalhas umedecidas", "compressas", "aspirador nasal", "termometro infantil", "xo febre", "soro infantil"], headlines: ["CUIDADO E CARINHO PARA O BEBÊ 💙", "TRANQUILIDADE PARA A FAMÍLIA 👶", "ITEM ESSENCIAL NA BOLSA DO BEBÊ 👜"] },
  { key: "pantufa-conforto", category: "FASHION", keywords: ["pantufa", "pantufas", "meia antiderrapante", "robe", "kimono"], headlines: ["CONFORTO PARA FICAR EM CASA 🏡", "QUENTINHO E ACONCHEGANTE 🧦", "O MIMO DOS DIAS FRIOS ❄️"] },
  { key: "plus-size", category: "FASHION", keywords: ["plus size", "moda plus", "conjunto plus size"], headlines: ["ESTILO EM TODOS OS TAMANHOS ✨", "CONFORTO E ATITUDE PARA O SEU CORPO 💖", "VALORIZA CADA CURVA 💃"] },
  { key: "viseira-chapeu", category: "FASHION", keywords: ["viseira", "chapeu de praia", "bone de aba reta", "bucket hat", "bandana", "porta niquel"], headlines: ["ESTILO E PROTEÇÃO NO SOL ☀️", "O DETALHE QUE COMPLETA O LOOK 😎", "PRÁTICO E CHEIO DE ESTILO ✨"] },
  { key: "cabelo-maluco", category: "FASHION", keywords: ["cabelo maluco", "fantasia infantil", "kit fantasia", "tiara de carnaval"], headlines: ["DIVERSÃO GARANTIDA NA FESTA 🎉", "SUCESSO NO DIA TEMÁTICO DA ESCOLA 🎭", "CRIATIVIDADE NO VISUAL ✨"] },
  { key: "racao-marcas", category: "PETS", keywords: ["bionatural", "katbom", "golden formula", "pedigree", "royal canin", "nestle purina", "purina", "guabi", "magnus", "three cats", "gran plus", "fn", "biofresh"], headlines: ["NUTRIÇÃO DE QUALIDADE PARA SEU PET 🐾", "RAÇÃO BOA COM PREÇO MELHOR AINDA 🛒", "CARINHO QUE COMEÇA NO POTINHO 🐶"] },
  { key: "leite-filhote", category: "PETS", keywords: ["leite para gatos", "leite para filhotes", "sucedaneo", "suplemento pet", "vitamina pet", "catosal"], headlines: ["CUIDADO ESPECIAL PARA OS FILHOTES 🐾", "CARINHO EM CADA REFEIÇÃO 🐱", "CARINHO EM FORMA DE ALIMENTO 🍼"] },
  { key: "cercado-pet", category: "PETS", keywords: ["cercado pet", "cercado", "grade pet", "portao pet", "rampa pet", "rampa", "escada pet"], headlines: ["SEGURANÇA E LIBERDADE PARA O SEU PET 🐶", "SEU PET PROTEGIDO EM CASA 🐾", "PRATICIDADE PARA O DIA A DIA DO PET ✨"] },
  { key: "tosa-pet", category: "PETS", keywords: ["maquina de tosa", "tosador", "aparador pet", "protetor de ouvido pet", "abafador pet"], headlines: ["TOSA EM CASA SEM ESTRESSE ✂️", "PET BEM CUIDADO SEM SAIR DE CASA 🐶", "ECONOMIA NO PET SHOP 💰"] },
  { key: "comedouro-interativo", category: "PETS", keywords: ["comedouro interativo", "dispensador de comida", "tigela lenta", "comedouro lento", "tapete de lamber", "tapete olfativo"], headlines: ["COMER DEVAGAR E SE DIVERTIR 🐶", "HORA DA RAÇÃO MAIS DIVERTIDA 🐾", "DIVERSÃO NA HORA DE COMER 🧩"] },
  { key: "raspador-lingua", category: "HEALTH", keywords: ["raspador de lingua", "escova dental", "escovas dentais", "kess", "escova interdental"], headlines: ["ROTINA DE HIGIENE BUCAL COMPLETA 😁", "CUIDADO DIÁRIO COM O SORRISO 🦷", "PRATICIDADE NA HIGIENE BUCAL ✨"] },
  { key: "lenco-desinfetante", category: "HEALTH", keywords: ["panos umedecidos", "alcool 70", "alcool em gel", "lenco antisseptico", "mascara descartavel", "luva descartavel"], headlines: ["HIGIENE PRÁTICA EM QUALQUER LUGAR 🧴", "PROTEÇÃO QUE CABE NA BOLSA ✨", "ESTOQUE COM PREÇO DE OPORTUNIDADE 🛒"] },
  { key: "dha-omega", category: "HEALTH", keywords: ["omegafor", "dha", "epa", "oleo de peixe", "krill"], headlines: ["PRATICIDADE NA SUA SUPLEMENTAÇÃO 💚", "UM CUIDADO A MAIS NO SEU DIA 🐟", "SUA ROTINA DE CUIDADOS MAIS PRÁTICA 🌿"] },
  { key: "odorizador-roupa", category: "HOME_KITCHEN_DECOR", keywords: ["odorizante de roupas", "agua de passar", "perfume para roupas", "comfort", "sachê perfumado"], headlines: ["ROUPAS CHEIROSAS POR MAIS TEMPO 🌸", "PERFUME QUE DURA NAS SUAS ROUPAS ✨", "FRESCOR NO GUARDA-ROUPA 👕"] },
  { key: "placa-sinalizacao", category: "HOME_KITCHEN_DECOR", keywords: ["placa pix", "placa qr code", "placa de sinalizacao", "placa decorativa", "placa", "plaquinha"], headlines: ["SEU NEGÓCIO MAIS PROFISSIONAL ✨", "IDENTIFICAÇÃO COM ESTILO 🪧", "PRATICIDADE QUE SEUS CLIENTES NOTAM 💳"] },
  { key: "kit-infantil-roupa", category: "KIDS_BABY", keywords: ["kit infantil", "conjunto infantil menina", "conjunto infantil menino", "roupa infantil", "pijama infantil"], headlines: ["LOOKS LINDOS PARA OS PEQUENOS 🧒", "CONFORTO PARA BRINCAR O DIA TODO ✨", "KIT COMPLETO COM PREÇO ÓTIMO 🛒"] },

  // ---------- Outros / gerais ----------
  { key: "automotivo", category: "OTHER", keywords: ["cera automotiva", "shampoo automotivo", "pretinho", "aromatizante automotivo", "capa de banco", "tapete automotivo", "kit lava rapido", "pneu", "oleo de motor", "palheta"], headlines: ["SEU CARRO BRILHANDO COMO NOVO 🚗", "CUIDADO QUE SEU CARRO MERECE ✨", "CARRO LIMPO, MOTORISTA FELIZ 🚘"] },
  { key: "papelaria", category: "OTHER", keywords: ["caderno", "agenda", "planner", "caneta", "marca texto", "lapis de cor", "canetinha", "bloco de notas", "post it", "fichario"], headlines: ["ORGANIZAÇÃO QUE INSPIRA ✏️", "PRODUTIVIDADE COM ESTILO 📒", "SEUS ESTUDOS MAIS COLORIDOS ✨"] },
  { key: "camping-viagem", category: "OTHER", keywords: ["barraca", "saco de dormir camping", "lanterna", "cooler", "caixa termica", "cadeira de praia", "guarda sol", "travesseiro de viagem"], headlines: ["AVENTURA SEM PERRENGUE 🏕️", "TUDO PRONTO PARA A PRÓXIMA VIAGEM 🌎", "CONFORTO EM QUALQUER LUGAR ⛺"] },
  { key: "bar-drinks", category: "OTHER", keywords: ["coqueteleira", "kit caipirinha", "kit bar", "dosador de bebidas", "balde de gelo", "forma de gelo"], headlines: ["DRINKS DE BARTENDER EM CASA 🍹", "SEU HAPPY HOUR MAIS ESTILOSO 🥂", "RECEBA OS AMIGOS COM CLASSE 🍸"] },
];

/** Sem tipo encontrado: headlines da categoria do produto. */
export const CATEGORY_HEADLINES: Record<Exclude<CatalogCategory, "OTHER">, string[]> = {
  FOOD_BEVERAGES: ["SABOR QUE CONQUISTA 😋", "PARA ABASTECER A DESPENSA COM ECONOMIA 🛒", "DELÍCIA COM PREÇO DE OPORTUNIDADE 😋", "O SABOR QUE A FAMÍLIA AMA 🍽️"],
  BEAUTY: ["SEU MOMENTO DE AUTOCUIDADO ✨", "SEU MOMENTO DE BELEZA EM PRIMEIRO LUGAR 💖", "O MIMO QUE VOCÊ MERECE 💅", "ROTINA DE BELEZA COMPLETA ✨"],
  HOME_KITCHEN_DECOR: ["SUA CASA MAIS PRÁTICA E BONITA 🏡", "O ACHADINHO QUE SUA CASA PEDIA ✨", "PRATICIDADE PARA O SEU LAR 🏡", "DETALHES QUE TRANSFORMAM A CASA 💛"],
  ELECTRONICS: ["TECNOLOGIA QUE FACILITA SUA VIDA ⚡", "UPGRADE COM PREÇO DE OPORTUNIDADE 📲", "INOVAÇÃO NA PALMA DA MÃO ⚡", "O GADGET QUE FALTAVA 🔌"],
  KIDS_BABY: ["ALEGRIA PARA OS PEQUENOS 🧸", "CUIDADO E CARINHO PARA O BEBÊ 💙", "DIVERSÃO GARANTIDA PARA A CRIANÇADA 🎈", "ACHADINHO PARA A FAMÍLIA DO BEBÊ 👶"],
  FASHION: ["ESTILO QUE COMBINA COM VOCÊ ✨", "LOOK NOVO SEM PESAR NO BOLSO 🛍️", "TENDÊNCIA COM PREÇO DE ACHADINHO 🔥", "A PEÇA QUE FALTAVA NO GUARDA-ROUPA 👗"],
  PETS: ["SEU PET MERECE O MELHOR 🐾", "MAIS ALEGRIA PARA O SEU MELHOR AMIGO 🐶", "CUIDADO COMPLETO PARA O SEU PET 🐱", "ACHADINHO PARA QUEM AMA PETS 🐾"],
  HEALTH: ["CUIDADO E PRATICIDADE PARA O SEU DIA 💚", "CUIDE DE VOCÊ COM PRATICIDADE 💚", "CONFORTO PARA A SUA ROTINA 🌿", "PRATICIDADE QUE CABE NA SUA ROTINA ⚡"],
};

/** Sem tipo nem categoria. */
export const GENERIC_HEADLINES = ["ACHADINHO IMPERDÍVEL 🔥", "OFERTA QUE VALE A PENA ✨", "PREÇO BOM DEMAIS PARA DEIXAR PASSAR 💥", "O ACHADINHO DO DIA 🛍️"];

/**
 * Desconto de 60% ou mais: entram também estas ({desconto} vira o número).
 * No máximo 1 headline de desconto a cada 3 posts no mesmo grupo.
 */
export const DISCOUNT_HEADLINES = [
  "{desconto}% OFF, PREÇO DE ERRO? 😱",
  "MENOS DA METADE DO PREÇO 🔥",
  "{desconto}% OFF SÓ HOJE ⏰",
  "{desconto}% DE DESCONTO, CORRE! 🏃",
  "DESCONTO DE {desconto}% QUE NÃO SE VÊ TODO DIA 💥",
  "PREÇO DESPENCOU: {desconto}% OFF 📉",
  "OFERTA RELÂMPAGO COM {desconto}% OFF ⚡",
];
export const DISCOUNT_HEADLINE_MIN_PCT = 60;
/** Headline de desconto: no máximo 1 a cada N posts do grupo. */
export const DISCOUNT_HEADLINE_EVERY = 3;
